# Forked from the Nim wrapper for SDL2, licensed under the MIT license
# Source: https://github.com/nim-lang/sdl2/blob/master/src/sdl2/private/keycodes.nim

type
  Scancode* {.size: sizeof(cint).} = enum
    SCANCODE_UNKNOWN = 0
    SCANCODE_A = 4, SCANCODE_B = 5, SCANCODE_C = 6,
    SCANCODE_D = 7, SCANCODE_E = 8, SCANCODE_F = 9,
    SCANCODE_G = 10, SCANCODE_H = 11, SCANCODE_I = 12,
    SCANCODE_J = 13, SCANCODE_K = 14, SCANCODE_L = 15,
    SCANCODE_M = 16, SCANCODE_N = 17, SCANCODE_O = 18,
    SCANCODE_P = 19, SCANCODE_Q = 20, SCANCODE_R = 21,
    SCANCODE_S = 22, SCANCODE_T = 23, SCANCODE_U = 24,
    SCANCODE_V = 25, SCANCODE_W = 26, SCANCODE_X = 27,
    SCANCODE_Y = 28, SCANCODE_Z = 29, SCANCODE_1 = 30,
    SCANCODE_2 = 31, SCANCODE_3 = 32, SCANCODE_4 = 33,
    SCANCODE_5 = 34, SCANCODE_6 = 35, SCANCODE_7 = 36,
    SCANCODE_8 = 37, SCANCODE_9 = 38, SCANCODE_0 = 39,
    SCANCODE_RETURN = 40, SCANCODE_ESCAPE = 41,
    SCANCODE_BACKSPACE = 42, SCANCODE_TAB = 43,
    SCANCODE_SPACE = 44, SCANCODE_MINUS = 45,
    SCANCODE_EQUALS = 46, SCANCODE_LEFTBRACKET = 47,
    SCANCODE_RIGHTBRACKET = 48, SCANCODE_BACKSLASH = 49,
    SCANCODE_NONUSHASH = 50, #
    SCANCODE_SEMICOLON = 51, SCANCODE_APOSTROPHE = 52, SCANCODE_GRAVE = 53,
    SCANCODE_COMMA = 54, SCANCODE_PERIOD = 55,
    SCANCODE_SLASH = 56, SCANCODE_CAPSLOCK = 57, SCANCODE_F1 = 58,
    SCANCODE_F2 = 59, SCANCODE_F3 = 60, SCANCODE_F4 = 61,
    SCANCODE_F5 = 62, SCANCODE_F6 = 63, SCANCODE_F7 = 64,
    SCANCODE_F8 = 65, SCANCODE_F9 = 66, SCANCODE_F10 = 67,
    SCANCODE_F11 = 68, SCANCODE_F12 = 69,
    SCANCODE_PRINTSCREEN = 70, SCANCODE_SCROLLLOCK = 71,
    SCANCODE_PAUSE = 72, SCANCODE_INSERT = 73,
    SCANCODE_HOME = 74, SCANCODE_PAGEUP = 75,
    SCANCODE_DELETE = 76, SCANCODE_END = 77,
    SCANCODE_PAGEDOWN = 78, SCANCODE_RIGHT = 79,
    SCANCODE_LEFT = 80, SCANCODE_DOWN = 81, SCANCODE_UP = 82, SCANCODE_NUMLOCKCLEAR = 83,
    SCANCODE_KP_DIVIDE = 84, SCANCODE_KP_MULTIPLY = 85,
    SCANCODE_KP_MINUS = 86, SCANCODE_KP_PLUS = 87,
    SCANCODE_KP_ENTER = 88, SCANCODE_KP_1 = 89,
    SCANCODE_KP_2 = 90, SCANCODE_KP_3 = 91, SCANCODE_KP_4 = 92,
    SCANCODE_KP_5 = 93, SCANCODE_KP_6 = 94, SCANCODE_KP_7 = 95,
    SCANCODE_KP_8 = 96, SCANCODE_KP_9 = 97, SCANCODE_KP_0 = 98,
    SCANCODE_KP_PERIOD = 99, SCANCODE_NONUSBACKSLASH = 100,
    SCANCODE_APPLICATION = 101, #*< windows contextual menu, compose
    SCANCODE_POWER = 102,
    SCANCODE_KP_EQUALS = 103, SCANCODE_F13 = 104,
    SCANCODE_F14 = 105, SCANCODE_F15 = 106, SCANCODE_F16 = 107,
    SCANCODE_F17 = 108, SCANCODE_F18 = 109, SCANCODE_F19 = 110,
    SCANCODE_F20 = 111, SCANCODE_F21 = 112, SCANCODE_F22 = 113,
    SCANCODE_F23 = 114, SCANCODE_F24 = 115,
    SCANCODE_EXECUTE = 116, SCANCODE_HELP = 117,
    SCANCODE_MENU = 118, SCANCODE_SELECT = 119,
    SCANCODE_STOP = 120, SCANCODE_AGAIN = 121, #*< redo
    SCANCODE_UNDO = 122, SCANCODE_CUT = 123, SCANCODE_COPY = 124,
    SCANCODE_PASTE = 125, SCANCODE_FIND = 126,
    SCANCODE_MUTE = 127, SCANCODE_VOLUMEUP = 128, SCANCODE_VOLUMEDOWN = 129,
    SCANCODE_KP_COMMA = 133, SCANCODE_KP_EQUALSAS400 = 134, SCANCODE_INTERNATIONAL1 = 135,
    SCANCODE_INTERNATIONAL2 = 136, SCANCODE_INTERNATIONAL3 = 137, #*< Yen
    SCANCODE_INTERNATIONAL4 = 138, SCANCODE_INTERNATIONAL5 = 139,
    SCANCODE_INTERNATIONAL6 = 140, SCANCODE_INTERNATIONAL7 = 141,
    SCANCODE_INTERNATIONAL8 = 142, SCANCODE_INTERNATIONAL9 = 143, SCANCODE_LANG1 = 144, #*< Hangul/English toggle
    SCANCODE_LANG2 = 145, #*< Hanja conversion
    SCANCODE_LANG3 = 146, #*< Katakana
    SCANCODE_LANG4 = 147, #*< Hiragana
    SCANCODE_LANG5 = 148, #*< Zenkaku/Hankaku
    SCANCODE_LANG6 = 149, #*< reserved
    SCANCODE_LANG7 = 150, #*< reserved
    SCANCODE_LANG8 = 151, #*< reserved
    SCANCODE_LANG9 = 152, #*< reserved
    SCANCODE_ALTERASE = 153, #*< Erase-Eaze
    SCANCODE_SYSREQ = 154, SCANCODE_CANCEL = 155,
    SCANCODE_CLEAR = 156, SCANCODE_PRIOR = 157,
    SCANCODE_RETURN2 = 158, SCANCODE_SEPARATOR = 159,
    SCANCODE_OUT = 160, SCANCODE_OPER = 161,
    SCANCODE_CLEARAGAIN = 162, SCANCODE_CRSEL = 163,
    SCANCODE_EXSEL = 164, SCANCODE_KP_00 = 176,
    SCANCODE_KP_000 = 177, SCANCODE_THOUSANDSSEPARATOR = 178,
    SCANCODE_DECIMALSEPARATOR = 179, SCANCODE_CURRENCYUNIT = 180,
    SCANCODE_CURRENCYSUBUNIT = 181, SCANCODE_KP_LEFTPAREN = 182,
    SCANCODE_KP_RIGHTPAREN = 183, SCANCODE_KP_LEFTBRACE = 184,
    SCANCODE_KP_RIGHTBRACE = 185, SCANCODE_KP_TAB = 186,
    SCANCODE_KP_BACKSPACE = 187, SCANCODE_KP_A = 188,
    SCANCODE_KP_B = 189, SCANCODE_KP_C = 190, SCANCODE_KP_D = 191,
    SCANCODE_KP_E = 192, SCANCODE_KP_F = 193,
    SCANCODE_KP_XOR = 194, SCANCODE_KP_POWER = 195,
    SCANCODE_KP_PERCENT = 196, SCANCODE_KP_LESS = 197,
    SCANCODE_KP_GREATER = 198, SCANCODE_KP_AMPERSAND = 199,
    SCANCODE_KP_DBLAMPERSAND = 200, SCANCODE_KP_VERTICALBAR = 201,
    SCANCODE_KP_DBLVERTICALBAR = 202, SCANCODE_KP_COLON = 203,
    SCANCODE_KP_HASH = 204, SCANCODE_KP_SPACE = 205,
    SCANCODE_KP_AT = 206, SCANCODE_KP_EXCLAM = 207,
    SCANCODE_KP_MEMSTORE = 208, SCANCODE_KP_MEMRECALL = 209,
    SCANCODE_KP_MEMCLEAR = 210, SCANCODE_KP_MEMADD = 211,
    SCANCODE_KP_MEMSUBTRACT = 212, SCANCODE_KP_MEMMULTIPLY = 213,
    SCANCODE_KP_MEMDIVIDE = 214, SCANCODE_KP_PLUSMINUS = 215,
    SCANCODE_KP_CLEAR = 216, SCANCODE_KP_CLEARENTRY = 217,
    SCANCODE_KP_BINARY = 218, SCANCODE_KP_OCTAL = 219,
    SCANCODE_KP_DECIMAL = 220, SCANCODE_KP_HEXADECIMAL = 221,
    SCANCODE_LCTRL = 224, SCANCODE_LSHIFT = 225, SCANCODE_LALT = 226, #*< alt, option
    SCANCODE_LGUI = 227, #*< windows, command (apple), meta
    SCANCODE_RCTRL = 228, SCANCODE_RSHIFT = 229, SCANCODE_RALT = 230, #*< alt gr, option
    SCANCODE_RGUI = 231, #*< windows, command (apple), meta
    SCANCODE_MODE = 257,
    SCANCODE_AUDIONEXT = 258, SCANCODE_AUDIOPREV = 259,
    SCANCODE_AUDIOSTOP = 260, SCANCODE_AUDIOPLAY = 261,
    SCANCODE_AUDIOMUTE = 262, SCANCODE_MEDIASELECT = 263,
    SCANCODE_WWW = 264, SCANCODE_MAIL = 265,
    SCANCODE_CALCULATOR = 266, SCANCODE_COMPUTER = 267,
    SCANCODE_AC_SEARCH = 268, SCANCODE_AC_HOME = 269,
    SCANCODE_AC_BACK = 270, SCANCODE_AC_FORWARD = 271,
    SCANCODE_AC_STOP = 272, SCANCODE_AC_REFRESH = 273, SCANCODE_AC_BOOKMARKS = 274,
    SCANCODE_BRIGHTNESSDOWN = 275, SCANCODE_BRIGHTNESSUP = 276, SCANCODE_DISPLAYSWITCH = 277,
    SCANCODE_KBDILLUMTOGGLE = 278, SCANCODE_KBDILLUMDOWN = 279,
    SCANCODE_KBDILLUMUP = 280, SCANCODE_EJECT = 281, SCANCODE_SLEEP = 282,
    NUM_SCANCODES = 512 #*< not a key, just marks the number of scancodes
                            #                                 for array bounds

const SDLK_SCANCODE_MASK = 1 shl 30
template SCANCODE_TO_KEYCODE(some: ScanCode): untyped = (some.cint or SDLK_SCANCODE_MASK)

const
  K_UNKNOWN*: cint = 0

  K_BACKSPACE*: cint = '\b'.cint
  K_TAB*: cint = '\t'.cint
  K_RETURN*: cint = '\r'.cint
  K_ESCAPE*: cint = '\27'.cint
  K_SPACE*: cint = ' '.cint
  K_EXCLAIM*: cint = '!'.cint
  K_QUOTEDBL*: cint = '"'.cint
  K_HASH*: cint = '#'.cint
  K_DOLLAR*: cint = '$'.cint
  K_PERCENT*: cint = '%'.cint
  K_AMPERSAND*: cint = '&'.cint
  K_QUOTE*: cint = '\''.cint
  K_LEFTPAREN*: cint = '('.cint
  K_RIGHTPAREN*: cint = ')'.cint
  K_ASTERISK*: cint = '*'.cint
  K_PLUS*: cint = '+'.cint
  K_COMMA*: cint = ','.cint
  K_MINUS*: cint = '-'.cint
  K_PERIOD*: cint = '.'.cint
  K_SLASH*: cint = '/'.cint
  K_0*: cint = '0'.cint
  K_1*: cint = '1'.cint
  K_2*: cint = '2'.cint
  K_3*: cint = '3'.cint
  K_4*: cint = '4'.cint
  K_5*: cint = '5'.cint
  K_6*: cint = '6'.cint
  K_7*: cint = '7'.cint
  K_8*: cint = '8'.cint
  K_9*: cint = '9'.cint
  K_COLON*: cint = ':'.cint
  K_SEMICOLON*: cint = ';'.cint
  K_LESS*: cint = '<'.cint
  K_EQUALS*: cint = '='.cint
  K_GREATER*: cint = '>'.cint
  K_QUESTION*: cint = '?'.cint
  K_AT*: cint = '@'.cint # Skip uppercase letters
  K_LEFTBRACKET*: cint = '['.cint
  K_BACKSLASH*: cint = '\\'.cint
  K_RIGHTBRACKET*: cint = ']'.cint
  K_CARET*: cint = '^'.cint
  K_UNDERSCORE*: cint = '_'.cint
  K_BACKQUOTE*: cint = '`'.cint
  K_a*: cint = 'a'.cint
  K_b*: cint = 'b'.cint
  K_c*: cint = 'c'.cint
  K_d*: cint = 'd'.cint
  K_e*: cint = 'e'.cint
  K_f*: cint = 'f'.cint
  K_g*: cint = 'g'.cint
  K_h*: cint = 'h'.cint
  K_i*: cint = 'i'.cint
  K_j*: cint = 'j'.cint
  K_k*: cint = 'k'.cint
  K_l*: cint = 'l'.cint
  K_m*: cint = 'm'.cint
  K_n*: cint = 'n'.cint
  K_o*: cint = 'o'.cint
  K_p*: cint = 'p'.cint
  K_q*: cint = 'q'.cint
  K_r*: cint =  'r'.cint
  K_s*: cint =  's'.cint
  K_t*: cint =  't'.cint
  K_u*: cint =  'u'.cint
  K_v*: cint =  'v'.cint
  K_w*: cint =  'w'.cint
  K_x*: cint =  'x'.cint
  K_y*: cint =  'y'.cint
  K_z*: cint =  'z'.cint

  K_DELETE*: cint =  '\127'.cint
  K_CAPSLOCK*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CAPSLOCK)

  K_F1*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F1)
  K_F2*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F2)
  K_F3*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F3)
  K_F4*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F4)
  K_F5*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F5)
  K_F6*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F6)
  K_F7*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F7)
  K_F8*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F8)
  K_F9*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F9)
  K_F10*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F10)
  K_F11*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F11)
  K_F12*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F12)

  K_PRINTSCREEN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_PRINTSCREEN)
  K_SCROLLLOCK*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_SCROLLLOCK)
  K_PAUSE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_PAUSE)
  K_INSERT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_INSERT)
  K_HOME*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_HOME)
  K_PAGEUP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_PAGEUP)
  K_END*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_END)
  K_PAGEDOWN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_PAGEDOWN)
  K_RIGHT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_RIGHT)
  K_LEFT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_LEFT)
  K_DOWN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_DOWN)
  K_UP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_UP)

  K_NUMLOCKCLEAR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_NUMLOCKCLEAR)
  K_KP_DIVIDE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_DIVIDE)
  K_KP_MULTIPLY*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MULTIPLY)
  K_KP_MINUS*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MINUS)
  K_KP_PLUS*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_PLUS)
  K_KP_ENTER*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_ENTER)
  K_KP_1*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_1)
  K_KP_2*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_2)
  K_KP_3*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_3)
  K_KP_4*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_4)
  K_KP_5*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_5)
  K_KP_6*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_6)
  K_KP_7*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_7)
  K_KP_8*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_8)
  K_KP_9*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_9)
  K_KP_0*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_0)
  K_KP_PERIOD*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_PERIOD)

  K_APPLICATION*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_APPLICATION)
  K_POWER*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_POWER)
  K_KP_EQUALS*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_EQUALS)
  K_F13*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F13)
  K_F14*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F14)
  K_F15*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F15)
  K_F16*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F16)
  K_F17*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F17)
  K_F18*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F18)
  K_F19*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F19)
  K_F20*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F20)
  K_F21*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F21)
  K_F22*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F22)
  K_F23*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F23)
  K_F24*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_F24)
  K_EXECUTE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_EXECUTE)
  K_HELP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_HELP)
  K_MENU*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_MENU)
  K_SELECT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_SELECT)
  K_STOP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_STOP)
  K_AGAIN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AGAIN)
  K_UNDO*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_UNDO)
  K_CUT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CUT)
  K_COPY*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_COPY)
  K_PASTE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_PASTE)
  K_FIND*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_FIND)
  K_MUTE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_MUTE)
  K_VOLUMEUP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_VOLUMEUP)
  K_VOLUMEDOWN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_VOLUMEDOWN)
  K_KP_COMMA*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_COMMA)
  K_KP_EQUALSAS400*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_EQUALSAS400)

  K_ALTERASE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_ALTERASE)
  K_SYSREQ*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_SYSREQ)
  K_CANCEL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CANCEL)
  K_CLEAR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CLEAR)
  K_PRIOR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_PRIOR)
  K_RETURN2*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_RETURN2)
  K_SEPARATOR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_SEPARATOR)
  K_OUT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_OUT)
  K_OPER*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_OPER)
  K_CLEARAGAIN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CLEARAGAIN)
  K_CRSEL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CRSEL)
  K_EXSEL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_EXSEL)

  K_KP_00*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_00)
  K_KP_000*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_000)
  K_THOUSANDSSEPARATOR*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_THOUSANDSSEPARATOR)
  K_DECIMALSEPARATOR*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_DECIMALSEPARATOR)
  K_CURRENCYUNIT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CURRENCYUNIT)
  K_CURRENCYSUBUNIT*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_CURRENCYSUBUNIT)
  K_KP_LEFTPAREN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_LEFTPAREN)
  K_KP_RIGHTPAREN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_RIGHTPAREN)
  K_KP_LEFTBRACE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_LEFTBRACE)
  K_KP_RIGHTBRACE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_RIGHTBRACE)
  K_KP_TAB*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_TAB)
  K_KP_BACKSPACE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_BACKSPACE)
  K_KP_A*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_A)
  K_KP_B*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_B)
  K_KP_C*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_C)
  K_KP_D*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_D)
  K_KP_E*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_E)
  K_KP_F*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_F)
  K_KP_XOR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_XOR)
  K_KP_POWER*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_POWER)
  K_KP_PERCENT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_PERCENT)
  K_KP_LESS*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_LESS)
  K_KP_GREATER*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_GREATER)
  K_KP_AMPERSAND*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_AMPERSAND)
  K_KP_DBLAMPERSAND*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_DBLAMPERSAND)
  K_KP_VERTICALBAR*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_VERTICALBAR)
  K_KP_DBLVERTICALBAR*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_DBLVERTICALBAR)
  K_KP_COLON*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_COLON)
  K_KP_HASH*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_HASH)
  K_KP_SPACE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_SPACE)
  K_KP_AT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_AT)
  K_KP_EXCLAM*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_EXCLAM)
  K_KP_MEMSTORE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMSTORE)
  K_KP_MEMRECALL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMRECALL)
  K_KP_MEMCLEAR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMCLEAR)
  K_KP_MEMADD*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMADD)
  K_KP_MEMSUBTRACT*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMSUBTRACT)
  K_KP_MEMMULTIPLY*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMMULTIPLY)
  K_KP_MEMDIVIDE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_MEMDIVIDE)
  K_KP_PLUSMINUS*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_PLUSMINUS)
  K_KP_CLEAR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_CLEAR)
  K_KP_CLEARENTRY*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_CLEARENTRY)
  K_KP_BINARY*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_BINARY)
  K_KP_OCTAL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_OCTAL)
  K_KP_DECIMAL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KP_DECIMAL)
  K_KP_HEXADECIMAL*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KP_HEXADECIMAL)

  K_LCTRL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_LCTRL)
  K_LSHIFT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_LSHIFT)
  K_LALT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_LALT)
  K_LGUI*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_LGUI)
  K_RCTRL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_RCTRL)
  K_RSHIFT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_RSHIFT)
  K_RALT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_RALT)
  K_RGUI*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_RGUI)

  K_MODE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_MODE)

  K_AUDIONEXT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AUDIONEXT)
  K_AUDIOPREV*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AUDIOPREV)
  K_AUDIOSTOP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AUDIOSTOP)
  K_AUDIOPLAY*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AUDIOPLAY)
  K_AUDIOMUTE*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AUDIOMUTE)
  K_MEDIASELECT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_MEDIASELECT)
  K_WWW*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_WWW)
  K_MAIL*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_MAIL)
  K_CALCULATOR*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_CALCULATOR)
  K_COMPUTER*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_COMPUTER)
  K_AC_SEARCH*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_SEARCH)
  K_AC_HOME*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_HOME)
  K_AC_BACK*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_BACK)
  K_AC_FORWARD*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_FORWARD)
  K_AC_STOP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_STOP)
  K_AC_REFRESH*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_REFRESH)
  K_AC_BOOKMARKS*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_AC_BOOKMARKS)

  K_BRIGHTNESSDOWN*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_BRIGHTNESSDOWN)
  K_BRIGHTNESSUP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_BRIGHTNESSUP)
  K_DISPLAYSWITCH*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_DISPLAYSWITCH)
  K_KBDILLUMTOGGLE*: cint =
    SCANCODE_TO_KEYCODE(SCANCODE_KBDILLUMTOGGLE)
  K_KBDILLUMDOWN*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KBDILLUMDOWN)
  K_KBDILLUMUP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_KBDILLUMUP)
  K_EJECT*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_EJECT)
  K_SLEEP*: cint =  SCANCODE_TO_KEYCODE(SCANCODE_SLEEP)

type
  Keymod* {.size: sizeof(cint).} = enum
    KMOD_NONE = 0x0000, KMOD_LSHIFT = 0x0001, KMOD_RSHIFT = 0x0002,
    KMOD_LCTRL= 0x0040, KMOD_RCTRL  = 0x0080, KMOD_LALT   = 0x0100,
    KMOD_RALT = 0x0200, KMOD_LGUI   = 0x0400, KMOD_RGUI   = 0x0800,
    KMOD_NUM  = 0x1000, KMOD_CAPS   = 0x2000, KMOD_MODE   = 0x4000,
    KMOD_RESERVED=0x8000

converter toInt*(some: Keymod): cint = cint(some)

template KMOD_CTRL*: untyped = (KMOD_LCTRL or KMOD_RCTRL)
template KMOD_SHIFT*:untyped = (KMOD_LSHIFT or KMOD_RSHIFT)
template KMOD_ALT*: untyped = (KMOD_LALT or KMOD_RALT)
template KMOD_GUI*: untyped = (KMOD_LGUI or KMOD_RGUI)

{.deprecated: [TScancode: Scancode].}
{.deprecated: [TKeymod: Keymod].}
